language: node_js

node_js:
  - "5"

sudo: false
compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm rebuild node-sass
  - npm run lint
  - npm test
  - npm run test-node
  - npm run build
